import { evaluateCondition } from "../../schema/conditions";
import { evaluateValidation } from "../../schema/validations";

// Embeds the ACTUAL runtime function bodies (fn.toString()) rather than a
// hand-ported copy: by the time this code executes in the browser, Vite has
// already compiled these functions down to plain JS, so this is byte-for-byte
// the same logic the React preview runs — zero drift, by construction.
export function buildFormJs(): string {
  return `"use strict";
// Generated by Form Builder. Do not edit by hand — regenerate from the form definition instead.

var evaluateCondition = ${evaluateCondition.toString()};

var evaluateValidation = ${evaluateValidation.toString()};

window.FormRuntime = (function () {
  var formDefinition = null;
  var strings = null;
  var currentLocale = null;

  function t(key) {
    var table = strings[currentLocale] || {};
    if (table[key] !== undefined) return table[key];
    var fallback = strings[formDefinition.defaultLocale] || {};
    return fallback[key] !== undefined ? fallback[key] : "";
  }

  function isStructural(fieldDef) {
    return fieldDef.type === "heading" || fieldDef.type === "paragraph";
  }

<<<<<<< HEAD
=======
  function callingCodeSelect(fieldDef) {
    return document.getElementById("field-" + fieldDef.id + "-calling");
  }

>>>>>>> 569474c (update project)
  function getFieldValue(fieldDef) {
    if (fieldDef.type === "checkbox") {
      var cb = document.querySelector('[name="' + fieldDef.name + '"]');
      return cb && cb.checked ? "true" : "";
    }
    if (fieldDef.type === "radio") {
      var checked = document.querySelector('[name="' + fieldDef.name + '"]:checked');
      return checked ? checked.value : "";
    }
    var el = document.querySelector('[name="' + fieldDef.name + '"]');
    return el ? el.value : "";
  }

  function setFieldValue(fieldDef, value) {
    if (fieldDef.type === "checkbox") {
      var cb = document.querySelector('[name="' + fieldDef.name + '"]');
      if (cb) cb.checked = value === "true";
      return;
    }
    if (fieldDef.type === "radio") {
      var radio = document.querySelector('[name="' + fieldDef.name + '"][value="' + value + '"]');
      if (radio) radio.checked = true;
      return;
    }
    var el = document.querySelector('[name="' + fieldDef.name + '"]');
    if (el) el.value = value;
  }

  function getValues() {
    if (!formDefinition) return null;
    var values = {};
    formDefinition.fields.forEach(function (f) {
      if (isStructural(f)) return;
      values[f.id] = getFieldValue(f);
<<<<<<< HEAD
=======
      if (f.type === "phone") {
        var select = callingCodeSelect(f);
        values[f.id + "__callingCode"] = select ? select.value : "";
      }
>>>>>>> 569474c (update project)
    });
    return values;
  }

  function setValues(values) {
    formDefinition.fields.forEach(function (f) {
      if (isStructural(f) || values[f.id] === undefined) return;
      setFieldValue(f, values[f.id]);
<<<<<<< HEAD
=======
      if (f.type === "phone") {
        var select = callingCodeSelect(f);
        if (select && values[f.id + "__callingCode"] !== undefined) select.value = values[f.id + "__callingCode"];
      }
>>>>>>> 569474c (update project)
    });
  }

  function evaluateAllConditions() {
    var values = {};
    formDefinition.fields.forEach(function (f) {
      if (!isStructural(f)) values[f.id] = getFieldValue(f);
    });

    formDefinition.fields.forEach(function (fieldDef) {
      var wrapper = document.getElementById("field-wrapper-" + fieldDef.id);
      if (!wrapper) return;

      var state = { visible: true, enabled: true, required: fieldDef.required };
      var rule = fieldDef.conditions[0];

      if (rule) {
        var currentValue = values[rule.sourceFieldId] || "";
        var matches = evaluateCondition(rule.operator, currentValue, rule.value);
        switch (rule.action) {
          case "show":
            state.visible = matches;
            break;
          case "hide":
            state.visible = !matches;
            break;
          case "enable":
            state.enabled = matches;
            break;
          case "disable":
            state.enabled = !matches;
            break;
          case "require":
            state.required = matches ? true : fieldDef.required;
            break;
          case "optional":
            state.required = matches ? false : fieldDef.required;
            break;
        }
      }

      wrapper.hidden = !state.visible;
      var controls = wrapper.querySelectorAll('[name="' + fieldDef.name + '"]');
      controls.forEach(function (el) {
        el.disabled = !state.enabled;
        el.required = state.required;
      });
<<<<<<< HEAD
      var marker = wrapper.querySelector(".required-marker");
=======
      if (fieldDef.type === "phone") {
        var select = callingCodeSelect(fieldDef);
        if (select) select.disabled = !state.enabled;
      }
      var marker = wrapper.querySelector(".star");
>>>>>>> 569474c (update project)
      if (marker) marker.hidden = !state.required;
    });
  }

  function validateField(fieldDef) {
    var errorEl = document.getElementById("error-" + fieldDef.id);
    if (!errorEl) return true;
    var wrapper = document.getElementById("field-wrapper-" + fieldDef.id);
    if (wrapper && wrapper.hidden) {
      errorEl.textContent = "";
      return true;
    }

    var value = getFieldValue(fieldDef);
    var rules = fieldDef.validations.slice();
    if (fieldDef.required) rules = [{ id: "__required", type: "required" }].concat(rules);

    for (var i = 0; i < rules.length; i++) {
      var rule = rules[i];
      if (!evaluateValidation(rule.type, value, rule.param)) {
        errorEl.textContent = rule.id === "__required" ? t("field_" + fieldDef.id + "_required_msg") : t("field_" + fieldDef.id + "_val_" + rule.id);
        return false;
      }
    }
    errorEl.textContent = "";
    return true;
  }

  function validateForm() {
    var allValid = true;
    formDefinition.fields.forEach(function (f) {
      if (isStructural(f)) return;
      var wrapper = document.getElementById("field-wrapper-" + f.id);
      if (wrapper && wrapper.hidden) return;
      if (!validateField(f)) allValid = false;
    });
    return allValid;
  }

  function attach(defn, strs, locale) {
    formDefinition = defn;
    strings = strs;
    currentLocale = locale;

    formDefinition.fields.forEach(function (fieldDef) {
      if (isStructural(fieldDef)) return;
      var controls = document.querySelectorAll('[name="' + fieldDef.name + '"]');
<<<<<<< HEAD
=======
      if (fieldDef.type === "phone") {
        var select = callingCodeSelect(fieldDef);
        if (select) controls = Array.prototype.slice.call(controls).concat([select]);
      }
>>>>>>> 569474c (update project)
      controls.forEach(function (el) {
        el.addEventListener("input", function () {
          evaluateAllConditions();
          validateField(fieldDef);
        });
        el.addEventListener("change", function () {
          evaluateAllConditions();
          validateField(fieldDef);
        });
      });
    });

    var formEl = document.getElementById("the-form");
    var successPanel = document.getElementById("success-panel");
    formEl.onsubmit = function (e) {
      e.preventDefault();
      if (!validateForm()) return;

      var data = {};
      formDefinition.fields.forEach(function (f) {
<<<<<<< HEAD
        if (!isStructural(f)) data[f.name] = getFieldValue(f);
=======
        if (isStructural(f)) return;
        data[f.name] = getFieldValue(f);
        if (f.type === "phone") {
          var select = callingCodeSelect(f);
          data[f.name + "CallingCode"] = select ? select.value : "";
        }
>>>>>>> 569474c (update project)
      });

      // TODO: wire to your backend endpoint here
      console.log("Form submission (no backend configured):", data);

      successPanel.hidden = false;
      successPanel.textContent = t("ui_success");
      formEl.hidden = true;
    };

    evaluateAllConditions();
  }

  return {
    attach: attach,
    evaluateAllConditions: evaluateAllConditions,
    validateForm: validateForm,
    getValues: getValues,
    setValues: setValues,
  };
})();
`;
}
