import { RTL_LANGS } from "../../form/langNames.ts";
import type { FileNames } from "../fileNames.ts";
import type { GeneratedFile } from "../types.ts";

/**
 * Builds `behavior.js`: a single script shared by both the FF and OC HTML variants
 * (branching internally on `document.body.dataset.variant`), unlike the reference's
 * `_FF.js`/`_OC.js` pair which largely duplicate the same logic. Content is the same
 * for every generated form — all per-form data lives in `data.js` (`FORM_DATA`),
 * read by this script at runtime — so this function takes no arguments.
 *
 * Responsibilities: `?lang=` resolution, `dir`/`lang` attribute setting (the reference
 * has no real RTL handling at all — this is new logic), populating all text from
 * FORM_DATA (mirroring the reference's empty-HTML + jQuery-injection convention),
 * building the calling-code dropdown, client-side validation (native + Parsley),
 * enable/disable submit, the submit-intent modal, and submission (only posting to
 * `FORM_DATA.param.apiEndpoint` when the builder configured one — otherwise validation
 * still runs and the thank-you state still shows, so an unconfigured endpoint isn't a
 * silent no-op).
 */
export function buildBehaviorJs(fileNames: FileNames): GeneratedFile {
  const contents = `/* Generated by Form Builder. Do not edit by hand. */
(function () {
  "use strict";

  var RTL_LANGS = ${JSON.stringify(RTL_LANGS)};

  function getLanguage() {
    // The builder's live preview runs this document from a blob: URL, which can't
    // carry a meaningful "?lang=" query string (appending one doesn't resolve), so the
    // preview sets this global directly instead. The real generated/downloaded form is
    // opened from a normal http(s)/file URL where "?lang=" works as documented.
    if (window.__PREVIEW_LANG__) return window.__PREVIEW_LANG__;
    var params = new URLSearchParams(window.location.search);
    return params.get("lang") || FORM_DATA.param.fallbackLanguage;
  }

  var language = getLanguage();
  if (!FORM_DATA.fields[language]) language = FORM_DATA.param.fallbackLanguage;

  function langSubtag(locale) {
    var i = locale.indexOf("_");
    return i === -1 ? locale : locale.substring(0, i);
  }

  function setDirectionAndLang() {
    var subtag = langSubtag(language);
    document.documentElement.setAttribute("lang", subtag);
    document.documentElement.setAttribute("dir", RTL_LANGS.indexOf(subtag) !== -1 ? "rtl" : "ltr");
  }

  function setText(el, text) {
    if (el) el.textContent = text || "";
  }

  function populateProfileFields() {
    var fields = FORM_DATA.fields[language];
    ["email", "firstName", "lastName", "callingCode", "countryCode"].forEach(function (id) {
      var input = document.getElementById(id);
      if (!input) return;
      var wrap = input.closest(".form_text_bx");
      var labelSpan = wrap && wrap.querySelector(".form_label span:first-child");
      var text = fields.label[id];
      setText(labelSpan, text);
      if ("placeholder" in input) input.placeholder = text || "";
    });
    var mobileInput = document.getElementById("mobileNumber");
    if (mobileInput) mobileInput.placeholder = fields.label.callingCode || "";
  }

  function populateCallingCodeDropdown() {
    var select = document.getElementById("callingCode");
    if (!select) return;
    var fields = FORM_DATA.fields[language];
    select.innerHTML = "";
    var first = document.createElement("option");
    first.value = "";
    first.textContent = fields.callingCodeDropdownFirstEntry || "";
    first.disabled = true;
    first.selected = true;
    select.appendChild(first);
    FORM_DATA.calling_codes.forEach(function (entry) {
      var opt = document.createElement("option");
      opt.value = entry.callingCode;
      opt.setAttribute("data-country-code", entry.countryCode);
      opt.setAttribute("data-mobile-digits", entry.mobileDigits);
      opt.textContent = "+" + entry.callingCode + " " + entry.countryName;
      select.appendChild(opt);
    });
  }

  function populateQuestions() {
    var questions = FORM_DATA.questions[language];
    var answers = FORM_DATA.answers[language];
    document.querySelectorAll(".form_check_module").forEach(function (module) {
      var qId = module.id;
      var q = questions[qId];
      if (!q) return;
      setText(module.querySelector(".form_check_title h3 span"), q.heading);
      setText(module.querySelector(".form_check_title p"), q.subheading);
      module.querySelectorAll("input[type=radio], input[type=checkbox]").forEach(function (input) {
        var label = module.querySelector("label[for='" + input.id + "']");
        if (!label) return;
        var answer = answers[qId] ? answers[qId][input.value] : undefined;
        if (answer && typeof answer === "object") {
          setText(label.querySelector("p"), answer.label);
          var img = label.querySelector("img");
          if (img) {
            img.setAttribute("src", answer.image || "");
            img.setAttribute("alt", answer.imageAlt || "");
          }
        } else {
          setText(label.querySelector("p"), answer);
        }
      });
    });
  }

  function populatePageCopy() {
    var pageError = FORM_DATA.page_error[language] || {};
    var hrErr = document.getElementById("hrErr");
    if (hrErr) {
      setText(hrErr.querySelector("h3"), pageError.heading);
      var errLink = hrErr.querySelector("a");
      setText(errLink, pageError.subHeadingUrlText);
      if (errLink) errLink.setAttribute("href", pageError.subHeadingUrl || "");
    }
    var thankYou = FORM_DATA.fields[language].thankYou || {};
    var hrTy = document.getElementById("hrTy");
    if (hrTy) {
      setText(hrTy.querySelector("h3"), thankYou.heading);
      var tyLink = hrTy.querySelector("a");
      setText(tyLink, thankYou.subHeadingUrlText);
      if (tyLink) tyLink.setAttribute("href", thankYou.subHeadingUrl || "");
    }
  }

  function populateMisc() {
    var fields = FORM_DATA.fields[language];
    setText(document.getElementById("requiredFieldNote"), fields.requiredField);
    var submitBtn = document.getElementById("btnSubmit");
    setText(submitBtn, fields.submitButton);
    if (fields.privacyPolicy) {
      var privacyLabel = document.querySelector("label[for='privacyPolicy'] span:first-child");
      setText(privacyLabel, fields.privacyPolicy.text);
      var privacyLink = document.getElementById("privacyPolicyLink");
      if (privacyLink) privacyLink.setAttribute("href", fields.privacyPolicy.linkUrl || "#");
    }
    if (fields.marketingOptin) {
      setText(document.querySelector("label[for='subscribe'] span"), fields.marketingOptin.text);
    }
    if (fields.termsAndConditions) {
      var termsLink = document.getElementById("termsLink");
      setText(termsLink, fields.termsAndConditions.text);
      if (termsLink) termsLink.setAttribute("href", fields.termsAndConditions.url || "#");
    }
    var vm = FORM_DATA.validation_messages[language];
    setText(document.getElementById("submitIntentPopupMessage1"), vm.modalMessage1);
    setText(document.getElementById("submitIntentPopupMessage2"), vm.modalMessage2);
    setText(document.getElementById("submitIntentPopupYes"), vm.modalButtonYes);
    setText(document.getElementById("submitIntentPopupNo"), vm.modalButtonNo);
    document.querySelectorAll("[data-parsley-required], [data-parsley-type], [data-parsley-mobile-number-by-country]").forEach(function (el) {
      el.setAttribute("data-parsley-required-message", vm.requiredField);
      el.setAttribute("data-parsley-type-message", vm.email);
      el.setAttribute("data-parsley-mobile-number-by-country-message", vm.mobileNumber);
    });
  }

  function checkboxGroupsValid() {
    var ok = true;
    document.querySelectorAll(".form_check_list_wrap[id$='-errors']").forEach(function (group) {
      var checkboxes = group.querySelectorAll("input[type=checkbox]");
      if (checkboxes.length === 0) return;
      var anyChecked = Array.prototype.some.call(checkboxes, function (cb) {
        return cb.checked;
      });
      group.classList.toggle("has-error", !anyChecked);
      if (!anyChecked) ok = false;
    });
    return ok;
  }

  function validateForm() {
    var form = document.getElementById("dataForm");
    var nativelyValid = form.checkValidity();
    var checkboxesValid = checkboxGroupsValid();
    if (!nativelyValid) form.reportValidity();
    return nativelyValid && checkboxesValid;
  }

  function showOverlay() {
    var overlay = document.getElementById("overlay");
    if (overlay) overlay.style.display = "";
  }
  function hideOverlay() {
    var overlay = document.getElementById("overlay");
    if (overlay) overlay.style.display = "none";
  }

  function showSuccess() {
    hideOverlay();
    var main = document.querySelector(".container, .container_oc");
    if (main) main.style.display = "none";
    var hrTy = document.getElementById("hrTy");
    if (hrTy) hrTy.style.display = "";
  }

  function showError() {
    hideOverlay();
    var errBox = document.getElementById("apiError");
    if (errBox) {
      errBox.style.display = "";
      setText(errBox, FORM_DATA.validation_messages[language].requiredField);
    }
  }

  function collectFormData() {
    var form = document.getElementById("dataForm");
    var formData = new FormData(form);
    var payload = {};
    formData.forEach(function (value, key) {
      payload[key] = value;
    });
    var params = new URLSearchParams(window.location.search);
    payload.language = language;
    payload.recipientId = params.get("id") || "";
    payload.variant = document.body.getAttribute("data-variant");
    return payload;
  }

  function submitForm() {
    var endpoint = FORM_DATA.param.apiEndpoint;
    if (!endpoint) {
      // No endpoint configured: validation already passed, so show the thank-you
      // state locally rather than silently doing nothing.
      showSuccess();
      return;
    }
    showOverlay();
    fetch(endpoint, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(collectFormData()),
    })
      .then(function (res) {
        if (!res.ok) throw new Error("submit failed");
        showSuccess();
      })
      .catch(function () {
        showError();
      });
  }

  function closeSubmitModal() {
    var popup = document.getElementById("submitIntentPopup");
    if (popup) popup.classList.remove("popup--open");
  }

  function showSubmitModal() {
    var popup = document.getElementById("submitIntentPopup");
    if (!popup) {
      submitForm();
      return;
    }
    popup.classList.add("popup--open");
    var yes = document.getElementById("submitIntentPopupYes");
    var no = document.getElementById("submitIntentPopupNo");
    var closeBtn = popup.querySelector(".popup__close");
    function onYes() {
      closeSubmitModal();
      submitForm();
    }
    function onNo() {
      closeSubmitModal();
    }
    if (yes) yes.onclick = onYes;
    if (no) no.onclick = onNo;
    if (closeBtn) closeBtn.onclick = onNo;
  }

  function enableDisableSubmit() {
    var btn = document.getElementById("btnSubmit");
    if (!btn) return;
    var form = document.getElementById("dataForm");
    var ok = form.checkValidity() && checkboxGroupsValid();
    btn.disabled = !ok;
    btn.classList.toggle("disabled", !ok);
  }

  function preselectFromQueryParam() {
    // OC variant only: ?q01= preselects Q1's matching answer, mirroring the reference.
    if (document.body.getAttribute("data-variant") !== "oc") return;
    var params = new URLSearchParams(window.location.search);
    var q01 = params.get("q01");
    if (!q01) return;
    var input = document.getElementById("Q1" + q01);
    if (input) input.checked = true;
  }

  function silentPreRegister() {
    if (document.body.getAttribute("data-variant") !== "oc") return;
    if (!FORM_DATA.param.apiEndpoint) return;
    fetch(FORM_DATA.param.apiEndpoint, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(collectFormData()),
    }).catch(function () {
      /* best-effort; submit-time errors are surfaced separately */
    });
  }

  function attachEvents() {
    var form = document.getElementById("dataForm");
    form.addEventListener("input", enableDisableSubmit);
    form.addEventListener("change", enableDisableSubmit);
    form.addEventListener("submit", function (event) {
      event.preventDefault();
      if (!validateForm()) return;
      showSubmitModal();
    });
    document.querySelectorAll(".btn_clear").forEach(function (btn) {
      var input = btn.previousElementSibling;
      btn.addEventListener("click", function () {
        if (input) {
          input.value = "";
          enableDisableSubmit();
        }
      });
    });
  }

  function init() {
    setDirectionAndLang();
    populateProfileFields();
    populateCallingCodeDropdown();
    populateQuestions();
    populatePageCopy();
    populateMisc();
    attachEvents();
    preselectFromQueryParam();
    enableDisableSubmit();
    if (typeof jQuery !== "undefined" && jQuery.fn.parsley) {
      jQuery("#dataForm").parsley();
    }
    silentPreRegister();
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
`;
  return { path: fileNames.behaviorJs, contents };
}
