import type { FormDefinition } from "../../schema";
import { buildStrings } from "../buildStrings";
import { buildStructuralData } from "../buildStructuralData";

export function buildAppJs(form: FormDefinition): string {
  const structuralData = buildStructuralData(form);
  const strings = buildStrings(form);
  const locales = form.locales.map((l) => ({ code: l.code, label: l.label, direction: l.direction, isDefault: l.isDefault }));

  return `"use strict";
// Generated by Form Builder. Do not edit by hand — regenerate from the form definition instead.

var FORM_DEFINITION = ${JSON.stringify(structuralData, null, 2)};
var LOCALES = ${JSON.stringify(locales, null, 2)};
var STRINGS = ${JSON.stringify(strings, null, 2)};

function t(locale, key) {
  var table = STRINGS[locale] || {};
  if (table[key] !== undefined) return table[key];
  var fallback = STRINGS[FORM_DEFINITION.defaultLocale] || {};
  return fallback[key] !== undefined ? fallback[key] : "";
}

function localeByCode(code) {
  for (var i = 0; i < LOCALES.length; i++) {
    if (LOCALES[i].code === code) return LOCALES[i];
  }
  return LOCALES[0];
}

function createOptionControls(fieldDef, locale) {
  var wrap = document.createElement("div");
  wrap.className = "options-group";

  if (fieldDef.type === "radio") {
    (fieldDef.options || []).forEach(function (opt) {
      var row = document.createElement("label");
      row.className = "option-row";
      var input = document.createElement("input");
      input.type = "radio";
      input.name = fieldDef.name;
      input.value = opt.value;
      input.id = "field-" + fieldDef.id + "-" + opt.id;
      var span = document.createElement("span");
      span.textContent = t(locale, "field_" + fieldDef.id + "_opt_" + opt.id);
      row.appendChild(input);
      row.appendChild(span);
      wrap.appendChild(row);
    });
    return wrap;
  }

  var select = document.createElement("select");
  select.name = fieldDef.name;
  select.id = "field-" + fieldDef.id;
  var placeholder = document.createElement("option");
  placeholder.value = "";
  select.appendChild(placeholder);
  (fieldDef.options || []).forEach(function (opt) {
    var option = document.createElement("option");
    option.value = opt.value;
    option.textContent = t(locale, "field_" + fieldDef.id + "_opt_" + opt.id);
    select.appendChild(option);
  });
  wrap.appendChild(select);
  return wrap;
}

function createControl(fieldDef, locale) {
  if (fieldDef.type === "textarea") {
    var textarea = document.createElement("textarea");
    textarea.name = fieldDef.name;
    textarea.id = "field-" + fieldDef.id;
    if (fieldDef.hasPlaceholder) textarea.placeholder = t(locale, "field_" + fieldDef.id + "_placeholder");
    if (fieldDef.defaultValue) textarea.value = fieldDef.defaultValue;
    return textarea;
  }

  if (fieldDef.type === "dropdown" || fieldDef.type === "radio") {
    return createOptionControls(fieldDef, locale);
  }

  if (fieldDef.type === "checkbox") {
    var label = document.createElement("label");
    label.className = "checkbox-row";
    var input = document.createElement("input");
    input.type = "checkbox";
    input.name = fieldDef.name;
    input.id = "field-" + fieldDef.id;
    var span = document.createElement("span");
    span.textContent = t(locale, "field_" + fieldDef.id + "_label");
    label.appendChild(input);
    label.appendChild(span);
    return label;
  }

  var input = document.createElement("input");
  input.type = fieldDef.type === "number" ? "number" : fieldDef.type === "email" ? "email" : "text";
  input.name = fieldDef.name;
  input.id = "field-" + fieldDef.id;
  if (fieldDef.hasPlaceholder) input.placeholder = t(locale, "field_" + fieldDef.id + "_placeholder");
  if (fieldDef.defaultValue) input.value = fieldDef.defaultValue;
  return input;
}

function renderField(fieldDef, locale) {
  var wrapper = document.createElement("div");
  wrapper.className = "field-row width-" + fieldDef.width;
  wrapper.id = "field-wrapper-" + fieldDef.id;

  if (fieldDef.type === "heading") {
    var h2 = document.createElement("h2");
    h2.className = "field-heading";
    h2.textContent = t(locale, "field_" + fieldDef.id + "_label");
    wrapper.appendChild(h2);
    return wrapper;
  }

  if (fieldDef.type === "paragraph") {
    var p = document.createElement("p");
    p.className = "field-paragraph";
    p.textContent = t(locale, "field_" + fieldDef.id + "_label");
    wrapper.appendChild(p);
    return wrapper;
  }

  if (fieldDef.type !== "checkbox") {
    var label = document.createElement("label");
    label.className = "field-label";
    label.setAttribute("for", "field-" + fieldDef.id);
    label.textContent = t(locale, "field_" + fieldDef.id + "_label") + " ";
    var marker = document.createElement("span");
    marker.className = "required-marker";
    marker.textContent = t(locale, "ui_required_mark");
    marker.hidden = !fieldDef.required;
    label.appendChild(marker);
    wrapper.appendChild(label);
  }

  wrapper.appendChild(createControl(fieldDef, locale));

  if (fieldDef.hasHelp) {
    var help = document.createElement("p");
    help.className = "field-help";
    help.textContent = t(locale, "field_" + fieldDef.id + "_help");
    wrapper.appendChild(help);
  }

  var error = document.createElement("p");
  error.className = "field-error";
  error.id = "error-" + fieldDef.id;
  wrapper.appendChild(error);

  return wrapper;
}

function renderAll(locale) {
  var root = document.getElementById("form-root");
  root.innerHTML = "";
  FORM_DEFINITION.fields.forEach(function (fieldDef) {
    root.appendChild(renderField(fieldDef, locale));
  });

  document.getElementById("form-title").textContent = t(locale, "form_title");
  document.getElementById("form-description").textContent = t(locale, "form_description");
  document.getElementById("submit-button").textContent = t(locale, "ui_submit");
}

function applyLocale(locale) {
  var previousValues = window.FormRuntime ? window.FormRuntime.getValues() : null;

  document.documentElement.lang = locale;
  document.documentElement.dir = localeByCode(locale).direction;

  renderAll(locale);
  window.FormRuntime.attach(FORM_DEFINITION, STRINGS, locale);

  if (previousValues) window.FormRuntime.setValues(previousValues);
  window.FormRuntime.evaluateAllConditions();

  var successPanel = document.getElementById("success-panel");
  if (!successPanel.hidden) successPanel.textContent = t(locale, "ui_success");
}

document.addEventListener("DOMContentLoaded", function () {
  var switcher = document.getElementById("language-switcher");
  var defaultLocale = FORM_DEFINITION.defaultLocale;

  LOCALES.forEach(function (locale) {
    var option = document.createElement("option");
    option.value = locale.code;
    option.textContent = locale.label;
    if (locale.code === defaultLocale) option.selected = true;
    switcher.appendChild(option);
  });

  switcher.addEventListener("change", function (e) {
    applyLocale(e.target.value);
  });

  applyLocale(defaultLocale);
});
`;
}
