import type { FieldType } from "../schema";
import type { FieldTypeDescriptor } from "./types";

export const FIELD_REGISTRY: Record<FieldType, FieldTypeDescriptor> = {
  textbox: {
    type: "textbox",
    displayName: "Textbox",
    inputTag: "input",
    inputType: "text",
    supportsOptions: false,
    supportsPlaceholder: true,
    supportsRequired: true,
    supportsConditions: true,
    availableValidations: ["required", "minLength", "maxLength", "regex"],
    isStructural: false,
  },
  textarea: {
    type: "textarea",
    displayName: "Text Area",
    inputTag: "textarea",
    supportsOptions: false,
    supportsPlaceholder: true,
    supportsRequired: true,
    supportsConditions: true,
    availableValidations: ["required", "minLength", "maxLength", "regex"],
    isStructural: false,
  },
  number: {
    type: "number",
    displayName: "Number",
    inputTag: "input",
    inputType: "number",
    supportsOptions: false,
    supportsPlaceholder: true,
    supportsRequired: true,
    supportsConditions: true,
    availableValidations: ["required", "regex"],
    isStructural: false,
  },
  email: {
    type: "email",
    displayName: "Email",
    inputTag: "input",
    inputType: "email",
    supportsOptions: false,
    supportsPlaceholder: true,
    supportsRequired: true,
    supportsConditions: true,
    availableValidations: ["required", "email"],
    isStructural: false,
  },
  checkbox: {
    type: "checkbox",
    displayName: "Checkbox",
    inputTag: "input",
    inputType: "checkbox",
    supportsOptions: false,
    supportsPlaceholder: false,
    supportsRequired: true,
    supportsConditions: true,
    availableValidations: ["required"],
    isStructural: false,
  },
  radio: {
    type: "radio",
    displayName: "Radio Button",
    inputTag: "input",
    inputType: "radio",
    supportsOptions: true,
    supportsPlaceholder: false,
    supportsRequired: true,
    supportsConditions: true,
    availableValidations: ["required"],
    isStructural: false,
  },
  dropdown: {
    type: "dropdown",
    displayName: "Dropdown",
    inputTag: "select",
    supportsOptions: true,
    supportsPlaceholder: false,
    supportsRequired: true,
    supportsConditions: true,
    availableValidations: ["required"],
    isStructural: false,
  },
  heading: {
    type: "heading",
    displayName: "Heading",
    inputTag: "none",
    supportsOptions: false,
    supportsPlaceholder: false,
    supportsRequired: false,
    supportsConditions: true,
    availableValidations: [],
    isStructural: true,
  },
  paragraph: {
    type: "paragraph",
    displayName: "Paragraph",
    inputTag: "none",
    supportsOptions: false,
    supportsPlaceholder: false,
    supportsRequired: false,
    supportsConditions: true,
    availableValidations: [],
    isStructural: true,
  },
};

export const FIELD_TYPES_IN_PALETTE_ORDER: FieldType[] = [
  "heading",
  "paragraph",
  "textbox",
  "textarea",
  "number",
  "email",
  "checkbox",
  "radio",
  "dropdown",
];

export * from "./types";
