import type { FileNames } from "./fileNames.ts";
import type { FormVariant, GeneratedFile } from "./types.ts";

/**
 * Inlines the generated CSS/data-JS/behavior-JS into a single self-contained HTML
 * document for the live preview iframe. The iframe can't fetch same-directory
 * external `<link>`/`<script src>` references the way a real zip download can, so this
 * substitutes inline equivalents — same generated bytes, just inlined rather than
 * referenced, so the preview runs the actual generated behavior/data JS (not a
 * separately hand-written rendering path) and can never diverge from the downloaded
 * output. Takes the same `FileNames` the generator used, so the substitution always
 * targets whatever names were actually written into the HTML.
 */
export function buildPreviewDocument(
  files: GeneratedFile[],
  variant: FormVariant,
  previewLocale: string,
  fileNames: FileNames,
): string {
  const htmlPath = variant === "ff" ? fileNames.ffHtml : fileNames.ocHtml;
  const html = files.find((f) => f.path === htmlPath)?.contents;
  const css = files.find((f) => f.path === fileNames.css)?.contents ?? "";
  const dataJs = files.find((f) => f.path === fileNames.dataJs)?.contents ?? "";
  const behaviorJs = files.find((f) => f.path === fileNames.behaviorJs)?.contents ?? "";
  if (!html) throw new Error(`No generated ${htmlPath} file to preview.`);

  // The preview is served from a blob: URL, which can't carry a working "?lang="
  // query string — set the override global behavior.js's getLanguage() checks first.
  const langOverride = `<script>window.__PREVIEW_LANG__ = ${JSON.stringify(previewLocale)};</script>`;

  return html
    .replace(`<link rel="stylesheet" href="${fileNames.css}">`, `<style>${css}</style>`)
    .replace(`<script src="${fileNames.dataJs}"></script>`, `${langOverride}\n<script>${dataJs}</script>`)
    .replace(`<script src="${fileNames.behaviorJs}"></script>`, `<script>${behaviorJs}</script>`);
}
