import type { FileNames } from "./fileNames.ts";
import type { FormVariant, GeneratedFile } from "./types.ts";

/**
 * Inlines the generated CSS/data-JS/behavior-JS into a single self-contained HTML
 * document for the live preview iframe. The iframe can't fetch same-directory
 * external `<link>`/`<script src>` references the way a real zip download can, so this
 * substitutes inline equivalents — same generated bytes, just inlined rather than
 * referenced, so the preview runs the actual generated behavior/data JS (not a
 * separately hand-written rendering path) and can never diverge from the downloaded
 * output. Takes the same `FileNames` the generator used, so the substitution always
 * targets whatever names were actually written into the HTML.
 *
 * `previewLocale` is accepted but no longer wired into the iframe: the FF.js/OC.js
 * scripts are now byte-identical copies of the reference (see buildFfJs.ts/
 * buildOcJs.ts), which only ever resolve the language from a real `?lang=` URL query
 * parameter — something a `blob:` URL can't reliably carry. The preview always renders
 * the form's fallback/default locale; locale switching still works correctly on the
 * real downloaded/deployed form, which is what actually ships.
 */
export function buildPreviewDocument(
  files: GeneratedFile[],
  variant: FormVariant,
  _previewLocale: string,
  fileNames: FileNames,
): string {
  const htmlPath = variant === "ff" ? fileNames.ffHtml : fileNames.ocHtml;
  const jsPath = variant === "ff" ? fileNames.ffJs : fileNames.ocJs;
  const html = files.find((f) => f.path === htmlPath)?.contents;
  const css = files.find((f) => f.path === fileNames.css)?.contents ?? "";
  const dataJs = files.find((f) => f.path === fileNames.dataJs)?.contents ?? "";
  const behaviorJs = files.find((f) => f.path === jsPath)?.contents ?? "";
  if (!html) throw new Error(`No generated ${htmlPath} file to preview.`);

  return html
    .replace(`<link rel="stylesheet" href="${fileNames.css}">`, `<style>${css}</style>`)
    .replace(`<script src="${fileNames.dataJs}"></script>`, `<script>${dataJs}</script>`)
    .replace(`<script src="${jsPath}"></script>`, `<script>${behaviorJs}</script>`);
}
