-- Idempotent version of the DKMS PII-encryption schema migration for [Users].
-- Safe to run any number of times — already-applied statements are skipped.
-- (This has already been applied to the JANITHA-PC\SQLEXPRESS/Adobe-FC dev DB
-- as of this session; this file exists for re-running elsewhere, e.g. a
-- staging/production database, or a CI/deploy script.)

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'emailHash'
)
BEGIN
    ALTER TABLE [Users] ADD [emailHash] NVARCHAR(500) NULL;
END

IF EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
    JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ccu ON tc.CONSTRAINT_NAME = ccu.CONSTRAINT_NAME
    WHERE tc.TABLE_NAME = 'Users' AND tc.CONSTRAINT_TYPE = 'UNIQUE' AND ccu.COLUMN_NAME = 'email'
)
BEGIN
    DECLARE @constraintName NVARCHAR(200) = (
        SELECT TOP 1 tc.CONSTRAINT_NAME
        FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
        JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ccu ON tc.CONSTRAINT_NAME = ccu.CONSTRAINT_NAME
        WHERE tc.TABLE_NAME = 'Users' AND tc.CONSTRAINT_TYPE = 'UNIQUE' AND ccu.COLUMN_NAME = 'email'
    );
    EXEC('ALTER TABLE [Users] DROP CONSTRAINT [' + @constraintName + ']');
END

IF (SELECT CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'email') < 1000
BEGIN
    ALTER TABLE [Users] ALTER COLUMN [email] NVARCHAR(1000) NOT NULL;
END

IF (SELECT CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'firstName') < 1000
BEGIN
    ALTER TABLE [Users] ALTER COLUMN [firstName] NVARCHAR(1000) NULL;
END

IF (SELECT CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'lastName') < 1000
BEGIN
    ALTER TABLE [Users] ALTER COLUMN [lastName] NVARCHAR(1000) NULL;
END
